ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.nk.backend.ApplicationKt.module ]
    }
}

app {
    jwt {
        secret = "nk-dev-secret-change-in-production"
        secret = ${?JWT_SECRET}
        issuer = "nevsky-konditer"
        audience = "nk-users"
        expiresInDays = 7
    }
    db {
        path = "./data/app.db"
        path = ${?DB_PATH}
    }
    cors {
        origin = "*"
        origin = ${?CORS_ORIGIN}
    }
}
